server:
  bind:
    host: 0.0.0.0
    port: 8099
  # url: http://localhost:8099
  url: ${KOMMONITOR_PROCESSES_API_URL}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    # First language is the default language
    - en
  # cors: true
  pretty_print: true
  limit: 10
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  manager:
    name: pygeoapi_prefect.manager.PrefectManager
logging:
  level: ERROR

metadata:
  identification:
    title:
      en: KomMonitor Processes API
    description:
      en: KomMonitor Processes API provides scripts for processing KomMonitor related indicators and spatial resources
    keywords:
      en:
        - KomMonitor
        - monitoring
        - processing
        - geospatial
        - data
        - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://example.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: 52°North GmbH
    url: https://52north.org/
  contact:
    name: 52°North GmbH
    position: Geo-IT
    address: Martin-Luther-King-Weg 24
    city: Münster
    postalcode: 48155
    country: Germany
    email: info@52north.org
    url: https://52north.org/about-us/contact-us/

dynamic-resources: